pipeline {
    agent none

    environment {
        SONAR_URL    = "http://172.31.17.212:9000"
        DOCKER_IMAGE = "9916633130/ultimate-cicd:${BUILD_NUMBER}"
        GIT_REPO_NAME = "springboot-gitops-cicd"
        GIT_USER_NAME = "sganadi130"
    }

    stages {

        stage('Checkout') {
            agent any
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17'
                }
            }
            steps {
                sh '''
                    cd app
                    mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17'
                }
            }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                        cd app
                        mvn sonar:sonar \
                          -Dsonar.token=$SONAR_AUTH_TOKEN \
                          -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            agent any
            steps {
                sh '''
                    cd app
                    docker build -t $DOCKER_IMAGE .
                '''
            }
        }

        stage('Push Docker Image') {
            agent any
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-cred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            agent any
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git checkout main
                        git pull origin main

                        git config user.email "sganadi130@gmail.com"
                        git config user.name "sganadi130"

                        sed -i "s|9916633130/ultimate-cicd:.*|${DOCKER_IMAGE}|g" \
                        k8s/deployment.yaml

                        git add k8s/deployment.yaml

                        if git diff --cached --quiet; then
                            echo "No changes to commit."
                        else
                            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                            git push https://$GITHUB_TOKEN@github.com/$GIT_USER_NAME/$GIT_REPO_NAME.git main
                        fi
                    '''
                }
            }
        }
    }
}
